// Tipos de acción para obtener usuarios
export const FETCH_USUARIOS_REQUEST = 'FETCH_USUARIOS_REQUEST';
export const FETCH_USUARIOS_SUCCESS = 'FETCH_USUARIOS_SUCCESS';
export const FETCH_USUARIOS_ERROR = 'FETCH_USUARIOS_ERROR';
export const FETCH_APPROVED_USERS_REQUEST = 'FETCH_APPROVED_USERS_REQUEST';
export const FETCH_APPROVED_USERS_SUCCESS = 'FETCH_APPROVED_USERS_SUCCESS';
export const FETCH_APPROVED_USERS_FAILURE = 'FETCH_APPROVED_USERS_FAILURE';
export const FETCH_REJECTED_USERS_REQUEST = 'FETCH_REJECTED_USERS_REQUEST';
export const FETCH_REJECTED_USERS_SUCCESS = 'FETCH_REJECTED_USERS_SUCCESS';
export const FETCH_REJECTED_USERS_ERROR = 'FETCH_REJECTED_USERS_ERROR';
export const APPROVE_USER_REQUEST = 'APPROVE_USER_REQUEST';
export const APPROVE_USER_SUCCESS = 'APPROVE_USER_SUCCESS';
export const APPROVE_USER_ERROR = 'APPROVE_USER_ERROR';


// Tipos de acción para detalles del usuario
export const FETCH_USUARIO_DETAILS_REQUEST = 'FETCH_USUARIO_DETAILS_REQUEST';
export const FETCH_USUARIO_DETAILS_SUCCESS = 'FETCH_USUARIO_DETAILS_SUCCESS';
export const FETCH_USUARIO_DETAILS_ERROR = 'FETCH_USUARIO_DETAILS_ERROR';
export const FETCH_USUARIO_DETAILS_FAILURE = 'FETCH_USUARIO_DETAILS_FAILURE';

// Tipos de acción para login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

// Tipos de acción para registro
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

// Tipos de acción para agregar usuario
export const ADD_USUARIO_REQUEST = 'ADD_USUARIO_REQUEST';
export const ADD_USUARIO_SUCCESS = 'ADD_USUARIO_SUCCESS';
export const ADD_USUARIO_ERROR = 'ADD_USUARIO_ERROR';

// Tipos de acción para bienes
export const FETCH_BIENES = 'FETCH_BIENES';
export const ADD_BIEN = 'ADD_BIEN';
export const ADD_BIEN_ERROR = 'ADD_BIEN_ERROR';
export const FETCH_BIEN_DETAILS = 'FETCH_BIEN_DETAILS';
export const UPDATE_BIEN = 'UPDATE_BIEN';
export const FETCH_BIENES_REQUEST = 'FETCH_BIENES_REQUEST';
export const FETCH_BIENES_SUCCESS = 'FETCH_BIENES_SUCCESS';
export const FETCH_BIENES_ERROR = 'FETCH_BIENES_ERROR';
export const FETCH_BIEN_DETAILS_ERROR  = 'FETCH_BIEN_DETAILS_ERROR '
export const FETCH_BIEN_DETAILS_REQUEST = ' FETCH_BIEN_DETAILS_REQUEST'


// Tipos de acción para stock
export const FETCH_STOCK_REQUEST = 'FETCH_STOCK_REQUEST';
export const FETCH_STOCK_SUCCESS = 'FETCH_STOCK_SUCCESS';
export const FETCH_STOCK_ERROR = 'FETCH_STOCK_ERROR';
export const ADD_STOCK_REQUEST = 'ADD_STOCK_REQUEST';
export const ADD_STOCK_SUCCESS = 'ADD_STOCK_SUCCESS';
export const ADD_STOCK_ERROR = 'ADD_STOCK_ERROR';
export const UPDATE_STOCK_REQUEST = 'UPDATE_STOCK_REQUEST';
export const UPDATE_STOCK_SUCCESS = 'UPDATE_STOCK_SUCCESS';
export const UPDATE_STOCK_FAILURE = 'UPDATE_STOCK_FAILURE';
export const UPDATE_STOCK_ERROR = 'UPDATE_STOCK_ERROR';
export const DELETE_STOCK_REQUEST = 'DELETE_STOCK_REQUEST';
export const DELETE_STOCK_SUCCESS = 'DELETE_STOCK_SUCCESS';
export const DELETE_STOCK_ERROR = 'DELETE_STOCK_ERROR';

// Nuevos tipos de acción para compras y ventas
export const FETCH_COMPRAS_VENTAS_REQUEST = 'FETCH_COMPRAS_VENTAS_REQUEST';
export const FETCH_COMPRAS_VENTAS_SUCCESS = 'FETCH_COMPRAS_VENTAS_SUCCESS';
export const FETCH_COMPRAS_VENTAS_ERROR = 'FETCH_COMPRAS_VENTAS_ERROR';
export const ADD_COMPRAS_VENTAS_REQUEST = 'ADD_COMPRAS_VENTAS_REQUEST';
export const ADD_COMPRAS_VENTAS_SUCCESS = 'ADD_COMPRAS_VENTAS_SUCCESS';
export const ADD_COMPRAS_VENTAS_ERROR = 'ADD_COMPRAS_VENTAS_ERROR';

// Tipos de acción para registrar una venta
export const REGISTRAR_VENTA_EXITO = 'REGISTRAR_VENTA_EXITO';
export const REGISTRAR_VENTA_ERROR = 'REGISTRAR_VENTA_ERROR';

// Tipos de acción para registrar una compra
export const REGISTRAR_COMPRA_EXITO = 'REGISTRAR_COMPRA_EXITO';
export const REGISTRAR_COMPRA_ERROR = 'REGISTRAR_COMPRA_ERROR';
export const COMPRA_SUCCESS = 'COMPRA_SUCCESS';
export const COMPRA_ERROR = 'COMPRA_ERROR';
export const  REGISTRAR_COMPRA_REQUEST = 'REGISTRAR_COMPRA_REQUEST';



// Acción de búsqueda
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_ERROR = 'SEARCH_ERROR';

// Tipos de acción para resetear contraseña
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';

// Tipos de acción para eliminar usuario
export const DELETE_USUARIO_REQUEST = 'DELETE_USUARIO_REQUEST';
export const DELETE_USUARIO_SUCCESS = 'DELETE_USUARIO_SUCCESS';
export const DELETE_USUARIO_ERROR = 'DELETE_USUARIO_ERROR';

// Tipos de acción para asignar rol
export const ASSIGN_ROLE_REQUEST = 'ASSIGN_ROLE_REQUEST';
export const ASSIGN_ROLE_SUCCESS = 'ASSIGN_ROLE_SUCCESS';
export const ASSIGN_ROLE_ERROR = 'ASSIGN_ROLE_ERROR';

// Otros tipos de acción...
export const UPDATE_USUARIO_REQUEST = 'UPDATE_USUARIO_REQUEST';
export const UPDATE_USUARIO_SUCCESS = 'UPDATE_USUARIO_SUCCESS';
export const UPDATE_USUARIO_ERROR = 'UPDATE_USUARIO_ERROR';

// Tipos de acción para actualizar usuario (reemplaza a UPDATE_USUARIO si se requiere diferenciación)
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

// Tipos de acción para eliminar usuario (reemplaza a DELETE_USUARIO si se requiere diferenciación)
export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';

export const SET_USER_DETAILS = 'SET_USER_DETAILS';
export const UPDATE_STOCK = 'UPDATE_STOCK ';

export const FETCH_USUARIO_COMPRAS_VENTAS_REQUEST = 'FETCH_USUARIO_COMPRAS_VENTAS_REQUEST';
export const FETCH_USUARIO_COMPRAS_VENTAS_SUCCESS = 'FETCH_USUARIO_COMPRAS_VENTAS_SUCCESS';
export const FETCH_USUARIO_COMPRAS_VENTAS_ERROR = 'FETCH_USUARIO_COMPRAS_VENTAS_ERROR';

// Tipos de acción para obtener o crear vendedor
export const FETCH_OR_CREATE_VENDEDOR_REQUEST = 'FETCH_OR_CREATE_VENDEDOR_REQUEST';
export const FETCH_OR_CREATE_VENDEDOR_SUCCESS = 'FETCH_OR_CREATE_VENDEDOR_SUCCESS';
export const FETCH_OR_CREATE_VENDEDOR_ERROR = 'FETCH_OR_CREATE_VENDEDOR_ERROR';
export const BUSCAR_VENDEDOR_REQUEST = 'BUSCAR_VENDEDOR_REQUEST';
export const BUSCAR_VENDEDOR_SUCCESS = 'BUSCAR_VENDEDOR_SUCCESS';
export const BUSCAR_VENDEDOR_FAIL = 'BUSCAR_VENDEDOR_FAIL';

// actionTypes.js
export const ADD_BIEN_REQUEST = 'ADD_BIEN_REQUEST';
export const ADD_BIEN_SUCCESS = 'ADD_BIEN_SUCCESS';
export const ADD_BIEN_FAIL = 'ADD_BIEN_FAIL';

export const BUSCAR_USUARIO_DNI_REQUEST = 'BUSCAR_USUARIO_DNI_REQUEST';
export const BUSCAR_USUARIO_DNI_SUCCESS = 'BUSCAR_USUARIO_DNI_SUCCESS';
export const BUSCAR_USUARIO_DNI_ERROR = 'BUSCAR_USUARIO_DNI_ERROR';

// Tipos de acciones para transacciones
export const FETCH_TRANSACCIONES_REQUEST = 'FETCH_TRANSACCIONES_REQUEST';
export const FETCH_TRANSACCIONES_SUCCESS = 'FETCH_TRANSACCIONES_SUCCESS';
export const FETCH_TRANSACCIONES_ERROR = 'FETCH_TRANSACCIONES_ERROR';

export const FETCH_TRAZABILIDAD_REQUEST = 'FETCH_TRAZABILIDAD_REQUEST';
export const FETCH_TRAZABILIDAD_SUCCESS = 'FETCH_TRAZABILIDAD_SUCCESS';
export const FETCH_TRAZABILIDAD_ERROR = 'FETCH_TRAZABILIDAD_ERROR';

// actionTypes.js

export const FETCH_PENDING_REGISTRATIONS_REQUEST = 'FETCH_PENDING_REGISTRATIONS_REQUEST';
export const FETCH_PENDING_REGISTRATIONS_SUCCESS = 'FETCH_PENDING_REGISTRATIONS_SUCCESS';
export const FETCH_PENDING_REGISTRATIONS_ERROR = 'FETCH_PENDING_REGISTRATIONS_ERROR';
export const APPROVE_REGISTRATION_REQUEST = 'APPROVE_REGISTRATION_REQUEST';
export const APPROVE_REGISTRATION_SUCCESS = 'APPROVE_REGISTRATION_SUCCESS';
export const APPROVE_REGISTRATION_ERROR = 'APPROVE_REGISTRATION_ERROR';
export const DENY_REGISTRATION_REQUEST = 'DENY_REGISTRATION_REQUEST';
export const DENY_REGISTRATION_SUCCESS = 'DENY_REGISTRATION_SUCCESS';
export const DENY_REGISTRATION_ERROR = 'DENY_REGISTRATION_ERROR';

export const  CHECK_USER_SUCCESS = 'CHECK_USER_SUCCESS,';
export const  CHECK_USER_ERROR = 'CHECK_USER_ERROR';
export const CHECK_USER_REQUEST = 'CHECK_USER_REQUEST'





// src/redux/actions/actionTypes.js





